version: "3"

services:
  mediaserver:
    image: linktree
    ports:
      - "5001:5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
      APP_NAME: ${APP_NAME}
    volumes:
      - ./database.db:/app/database.db
      - ./static:/app/static
    restart: unless-stopped
